on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3

      - name: 'Login to Docker'
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_TOKEN}}
  
      - name: 'Image Building'
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/myymlimage .

      - name: 'Push image to Docker Hub'
        run: docker push ${{secrets.DOCKER_USERNAME}}/myymlimage